# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=()

source $ZSH/oh-my-zsh.sh

# Editor
export EDITOR=nvim

# Custom aliases
source ~/.aliases

# Custom functions
source ~/.functions

# zsh autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey -v
bindkey '^ ' autosuggest-accept
bindkey "^n" down-line-or-search
bindkey "^p" up-line-or-search

# Fast node version manager
eval "`fnm env`"

# Path
export PATH="$PATH:/usr/local/sbin:$GOPATH/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/Users/kevinrambaud/Library/Python/2.7/bin:/Users/kevinrambaud/Dev/flutter/bin"

# Go path
export GOPATH=$HOME/go
export GO111MODULE=auto
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"
eval "$(rbenv init -)"

export PATH=$PATH:/Users/kevinrambaud/.nexustools

